def get_empty_match() -> dict:
    return {'homeTeamGoals': 0,
            'awayTeamGoals': 0,
            'homeTeamHalftimeGoals': 0,
            'awayTeamHalftimeGoals': 0,
            '_id': '123',
            'leagueCode': 'E0',
            'leagueName': 'Dummy league',
            'countryName': 'Utopia',
            'currentRound': 99,
            'date': '11/11/11',
            'seasonYear': '11/11',
            'homeTeam': 'team1',
            'awayTeam': 'team2',
            'finalOutcome': 'H',
            'halfTimeOutcome': 'D'}
